# Generated by Django 5.2.7 on 2025-11-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('decano', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facultad_logos/')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('docente', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=100)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='curso_portadas/')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.facultad')),
            ],
        ),
    ]
